/**
 * Type definitions for Target Audience & Offer Generator
 * 
 * These types define the structure of strategic analysis data
 * generated by the Gemini API based on Alex Hormozi's Grand Slam Offer methodology.
 */

/**
 * Scored item with importance rating (1-10)
 * Used for desires, barriers, and needs
 */
export interface ScoredItem {
  text: string;
  score: number; // Integer between 1 and 10 inclusive
}

/**
 * Customer segment with complete desire/barrier/need analysis
 * Used for Perfect Customer (Mükemmel Müşteri) and Necessary Customer (Mecburi Müşteri)
 */
export interface CustomerSegment {
  profil: string;
  icselArzular: ScoredItem[]; // Internal desires (minimum 3)
  dissalArzular: ScoredItem[]; // External desires (minimum 3)
  icselEngeller: ScoredItem[]; // Internal barriers (minimum 3)
  dissalEngeller: ScoredItem[]; // External barriers (minimum 3)
  ihtiyaclar: ScoredItem[]; // Needs (minimum 3)
}

/**
 * Unnecessary customer profile (high effort, low profit)
 * Only contains profile description without detailed analysis
 */
export interface UnnecessaryCustomer {
  profil: string;
}

/**
 * Irresistible offers for each customer segment
 * Based on Alex Hormozi's Grand Slam Offer framework
 */
export interface IrresistibleOffers {
  mukemmelMusteriTeklif: string; // Offer for perfect customers
  mecburiMusteriTeklif: string; // Offer for necessary customers
  gereksizMusteriTeklif: string; // Filtering offer for unnecessary customers
}

/**
 * Complete strategic analysis structure
 * Contains all three customer segments and corresponding offers
 */
export interface StrategicAnalysis {
  mukemmelMusteri: CustomerSegment; // Perfect customer (low effort, high profit)
  mecburiMusteri: CustomerSegment; // Necessary customer (high effort, high profit)
  gereksizMusteri: UnnecessaryCustomer; // Unnecessary customer (high effort, low profit)
  reddedilemezTeklifler: IrresistibleOffers; // Irresistible offers for all segments
}

/**
 * Database record for stored target audience analysis
 * Includes metadata and complete analysis data
 */
export interface TargetAudienceAnalysis {
  id: string; // UUID
  user_id: string; // UUID - foreign key to auth.users
  industry: string; // Industry/sector input
  analysis_data: StrategicAnalysis; // Complete strategic analysis (JSONB)
  created_at: string; // ISO 8601 timestamp
}

/**
 * API request payload for analysis generation
 */
export interface TargetAudienceRequest {
  industry: string;
}

/**
 * API response for successful analysis generation
 */
export interface TargetAudienceResponse {
  success: true;
  analysis_id: string;
  analysis: StrategicAnalysis;
}

/**
 * API error response
 */
export interface TargetAudienceError {
  error: string; // Turkish error message
}
