-- Add new metric columns to meta_metrics table
ALTER TABLE meta_metrics
  ADD COLUMN IF NOT EXISTS conversations INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS messaging_conversations_started INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS link_clicks INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS landing_page_views INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS post_engagement INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS post_reactions INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS leads INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cost_per_lead DECIMAL(10,2),
  ADD COLUMN IF NOT EXISTS cost_per_conversation DECIMAL(10,2),
  ADD COLUMN IF NOT EXISTS objective VARCHAR(100);
